kind: golang.Generate
spec:
  versionPackagePath: internal/version
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
---
kind: common.Image
name: image-image-factory
spec:
  baseImage: alpine:3.20.3
  extraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
  additionalImages: []
  allowedLocalPaths:
    - tailwind.config.js
    - package.json
    - package-lock.json
  dependsOn:
    - tailwind
  customCommands:
    - apk add --no-cache --update
        bash
        cpio
        dosfstools
        e2fsprogs
        efibootmgr
        kmod
        mtools
        pigz
        qemu-img
        squashfs-tools
        tar
        util-linux
        xfsprogs
        xorriso
        xz
        zstd
  copyFrom:
    - stage: ghcr.io/siderolabs/grub:v1.9.0
      source: /
      destination: /
    - stage: ghcr.io/siderolabs/grub@sha256:4aea36c88627add06512a14c7e571b43405b6eeeca0a8ad295b8c4e31bf57721 # amd64
      source: /usr/lib/grub
      destination: /usr/lib/grub
    - stage: ghcr.io/siderolabs/grub@sha256:d82f11c8a7dc61fcdcc1d93d9550a1624eb291829a90700983e1c5b1a3b6cc26 # arm64
      source: /usr/lib/grub
      destination: /usr/lib/grub
    - stage: ghcr.io/siderolabs/installer:v1.9.1
      source: /usr/share/grub/unicode.pf2
      destination: /usr/share/grub/unicode.pf2
---
kind: auto.CustomSteps
spec:
  steps:
    - name: integration.test
      toplevel: true
    - name: integration
      toplevel: true
    - name: tailwind
      toplevel: true
---
kind: custom.Step
name: integration.test
spec:
  docker:
    enabled: true
    stages:
      - name: integration-build
        description: builds the integration test binary
        from: base
        steps:
          - script:
              command: go test -c -covermode=atomic -coverpkg=./... -tags integration ./internal/integration
              cache:
                - /root/.cache/go-build
                - /go/pkg
      - name: integration.test
        description: copies out the integration test binary
        steps:
          - copy:
              from: integration-build
              src: /src/integration.test
              dst: /integration.test
  makefile:
    enabled: true
    phony: true
    script:
      - "@$(MAKE) local-$@ DEST=$(ARTIFACTS)"
---
kind: custom.Step
name: integration
spec:
  makefile:
    enabled: true
    phony: true
    depends:
      - integration.test
    variables:
      - name: RUN_TESTS
        defaultValue: TestIntegration
      - name: TEST_FLAGS
        defaultValue: ""
    script:
      - "@$(MAKE) image-image-factory PUSH=true"
      - docker pull $(REGISTRY)/$(USERNAME)/image-factory:$(TAG)
      - docker run --rm --net=host --privileged -v /dev:/dev -v $(PWD)/$(ARTIFACTS)/integration.test:/bin/integration.test:ro --entrypoint /bin/integration.test $(REGISTRY)/$(USERNAME)/image-factory:$(TAG) -test.v $(TEST_FLAGS) -test.run $(RUN_TESTS)
  ghaction:
    enabled: true
    environment:
      REGISTRY: registry.dev.siderolabs.io
      TEST_FLAGS: "-test.schematic-service-repository=registry.dev.siderolabs.io/image-factory/schematic -test.installer-external-repository=registry.dev.siderolabs.io/siderolabs -test.installer-internal-repository=registry.dev.siderolabs.io/siderolabs -test.cache-repository=registry.dev.siderolabs.io/image-factory/cache"
---
kind: common.Build
spec:
  ignoredPaths:
    - node_modules/
---
kind: service.CodeCov
spec:
  targetThreshold: 9 # the actual coverage is much higher and reported from the integration test
---
kind: custom.Step
name: tailwind
spec:
  makefile:
    enabled: true
    phony: true
    script:
      - "@$(MAKE) local-tailwind-copy PUSH=false DEST=. PLATFORM=linux/amd64 BUILDKIT_MULTI_PLATFORM=0"
  docker:
    description: "Runs tailwind update"
    enabled: true
    stages:
      - name: tailwind-base
        description: "Installs tailwindcss"
        from: docker.io/node:21.7.3-alpine3.19
        workdir: /src
        steps:
          - copy:
              src: package.json package-lock.json
              dst: .
          - script:
              cache:
                - /src/node_modules
              command: npm ci
      - name: tailwind-update
        description: "tailwind update"
        from: tailwind-base
        steps:
          - copy:
              src: tailwind.config.js
              dst: .
          - copy:
              src: internal/frontend/http
              dst: internal/frontend/http
          - script:
              cache:
                - /src/node_modules
              command: node_modules/.bin/tailwindcss -i internal/frontend/http/css/input.css -o internal/frontend/http/css/output.css --minify
      - name: tailwind-copy
        description: "Copies assets"
        steps:
          - copy:
              from: tailwind-update
              src: /src/internal/frontend/http/css/output.css
              dst: internal/frontend/http/css/output.css
