# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/configuration-chainsaw-v1alpha2.json
apiVersion: chainsaw.kyverno.io/v1alpha2
kind: Configuration
metadata:
  name: image-factory-helm-chart
spec:
  timeouts:
    apply: 60s
    assert: 600s
    cleanup: 300s
    delete: 60s
    error: 60s
    exec: 600s
  execution:
    failFast: true
    parallel: 1
  templating:
    enabled: true
