name: default
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
"on":
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
jobs:
  default:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    if: (!startsWith(github.head_ref, 'renovate/') && !startsWith(github.head_ref, 'dependabot/'))
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
      - name: push-image-factory
        if: github.event_name != 'pull_request'
        env:
          PLATFORM: linux/amd64,linux/arm64
          PUSH: "true"
        run: |
          make image-image-factory REGISTRY=ghcr.io/${{ github.repository_owner }}
      - name: push-image-factory-latest
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        env:
          PLATFORM: linux/amd64,linux/arm64
          PUSH: "true"
        run: |
          make image-image-factory IMAGE_TAG=latest REGISTRY=ghcr.io/${{ github.repository_owner }}
