{{- if .Values.tls.create -}}
{{ $cert := .Values.tls.cert | required ".Values.tls.cert is required." }}
{{ $key := .Values.tls.key | required ".Values.tls.key is required." }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imageFactory.secretTls" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imageFactory.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.tls.ca }}
  ca.crt: |
    {{- .Values.tls.ca | nindent 4 }}
  {{- end }}
  tls.crt: |
    {{- $cert | nindent 4 }}
  tls.key: |
    {{- $key | nindent 4 }}
{{- end }}
