{{- if and .Values.config.authentication.enabled (not .Values.auth.existingSecret) }}
{{- $htpasswd := .Values.auth.htpasswd | required ".Values.auth.htpasswd is required when config.authentication.enabled=true and config.authentication.existingSecret is empty." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image-factory.fullname" . }}-htpasswd
  namespace: {{ include "image-factory.namespace" . }}
  labels:
    {{- include "image-factory.labels" . | nindent 4 }}
type: Opaque
stringData:
  htpasswd: |
    {{- $htpasswd | nindent 4 }}
{{- end }}
